# Generated by Django 5.2 on 2025-04-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_simplified', models.CharField(max_length=255, unique=True)),
                ('pinyin', models.CharField(blank=True, max_length=255, null=True)),
                ('definition_en', models.TextField(blank=True, null=True)),
                ('example_sentence_zh', models.TextField(blank=True, null=True)),
                ('example_sentence_en', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
